spring:
  application:
    name: consumer

server:
  port: 8080

producer:
  service:
    url: http://localhost:8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true