spring:
  application:
    name: configclient
#  If we comment out the below profiles then build info exist those values will be loaded as default.
#  profiles:
#    active: dev

# Default values will comment out and no active profiles properties are not existed
#  then application will failed to start if no active profile is set.
#build:
#  id: 101
#  version: 0.0.1
#  name: "Local Config build"
#  type: "Local"