spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/bhargav
      database: userdb
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb?currentSchema=public&TimeZone=Asia/Kolkata
#    username: bhargav
#    password: bhargav
#  jpa:
##    properties:
##      hibernate.jdbc.time_zone: Asia/Kolkata
#    datasource: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    ------------------------------------
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
server:
    port: 8082