spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
#  datasource:
#    url: jdbc:postgresql://localhost:5432/orderdb?currentSchema=public&TimeZone=Asia/Kolkata
#    username: bhargav
#    password: bhargav
#  h2:
#    console:
#      enabled: true
#  jpa:
#    datasource: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
server:
  port: 8083